props := $(filter-out 35,$(filter-out 34,$(filter-out 33,$(shell seq -w 1 50)))) 75 76 77 78 79 80 81 82 83
expensive_props = 33 34 35 84 85 86

prop_prefix = prop_T

targets :=

HIPSPEC_EXPENSIVE_FLAGS = --pvars --size 7

include ../Makefile.common

